[project]
name = "kindrahealth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.121.2",
    "pydantic[email]>=2.12.4",
    "pytest>=9.0.1",
]
